### PR TITLE
Throw exception if filename contains slash

### LINKED ISSUE #142: vfsStream::newFile allows slashes in filenames
Hi! If you do this:

```
sStream::setup();
vfsStream::newFile('text/mytext.txt', 0755)
    ->withContent("hello world")
    ->at($vfs_root);
vfsStream::newFile('notes/mynote.txt', 0755)
    ->withContent("hello world 2")
    ->at($vfs_root);

print_r(scandir($vfs_root->url()));
```

You will see:

```
Array
(
    [0] => .
    [1] => ..
    [2] => notes/mynote.txt
    [3] => text/mytext.txt
)
```

`scandir` doesn't recursively drill down into subdirectories - in this case it should output just the directory names, `notes` and `text`, not `notes/mynote.txt`. These files were created in the root folder, with slashes in the filenames, which is not allowed in a real filesystem.

Also, `scandir($vfs_root->url() . "/notes");` will throw an error as the notes directory does not exist.

As the intention is to create directories, I suggest either throw an error or create the intended directory.

Very useful filesystem mocking library by the way! We use it in a number of our projects. Cheers for the effort.

### PR DESCRIPTION
**Pull request by bizurkur**
- Throw exception if `vfsStreamFile` contains a slash in the name.
  - This resolves #142.
  - This is the same behavior that `vfsStreamDirectory` has.

### CODE REVIEW

File: src/main/php/org/bovigo/vfs/vfsStreamFile.php [hunk 1]
```diff
@@ -393,4 +397,19 @@ public function hasExclusiveLock($resource = null): bool
...
+
+    /**
+     * renames the content
+     *
+     * @param   string  $newName
+     * @throws  vfsStreamException
+     */
+    public function rename(string $newName)
+    {
+        if (strstr($newName, '/') !== false) {
```
Comment (allejo) [inline src/main/php/org/bovigo/vfs/vfsStreamFile.php]: Given that this makes `vfsStreamFile::rename()` and `vfsStreamDirectory::rename()` virtually identitical, could this check be moved to `vfsStreamAbstractContent::rename()` instead?

**Comment by allejo** [comment]
While we're on the topic of blacklisted characters in filenames... Should there be an array of blacklisted characters instead? I know `:` is a forbidden character at least on macOS and I think on Windows too.

File: src/main/php/org/bovigo/vfs/vfsStreamFile.php (hunk 1 above)
Comment (bizurkur) [reply src/main/php/org/bovigo/vfs/vfsStreamFile.php]: It could. I originally didn't because I wasn't trying to change the behavior of `vfsStreamBlock`, but I just noticed it extends `vfsStreamFile` and not the abstract so now all three share the same behavior. Definitely makes more sense moving it to the abstract.

**Comment by bizurkur** [comment]
As for other blacklisted characters, that sounds like something that should be done as a separate PR to me but possibly a good idea. I think the point of this issue was that allowing `/` gave the interpretation that it would automatically create a directory containing a file and that's not what happens.

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,7 @@
   * raised minimum required PHP version to 7.2.0
   * all methods of `org\bovigo\vfs\visitor\vfsStreamVisitor` are now declared with `self` as return type
   * `vfsStreamWrapper::setRoot()` and `vsfStreamWrapper::getRoot()` method signatures now require and return `org\bovigo\vfs\vfsStreamDirectory` vice `org\bovigo\vfs\vfsStreamContainer`.
+  * `vfsStream::newFile()` and `org\bovigo\vfs\vfsStreamFile` will throw an exception if the filename contains a forward slash (`/`).
```
Comment (allejo) [inline CHANGELOG.md]: Since `vfsStreamBlock` is marked as `@api`, should this entry also mention this new behavior?

Comment (bizurkur) [reply CHANGELOG.md]: Added
